<br />
<div id="unipay_simplepath">
    <div id="simplepath_unsported">
        <?= $block->escapeHtml(__('unipay.com is one of the most popular payment processors in Georgia, unipay Checkout extension provides the most integrated checkout experience possible with Magento to accept ewallet and credit card processing. ( Visa, Mastercard and AMEX )')); ?>
        <span class="note">
            <a href="https://www.unipay.com/support" target="_blank">
                (<?= $block->escapeHtml(__('More Information')); ?>)
            </a>
        </span>
    </div>
</div>